export const item_Actions= {
	item_Create :{
		NEW: "ADD_NEW",
		POST:"ADD_POST",
		FIND:"TODO_FIND",
		FAILURE: "ADD_FAILURE",
		NOT_AUTHORIZED: "LOGIN_ACCOUNT_NOT_AUTHORIZED",
	CREATED:"ADD_CREATED",
	'LOGOUT':"LOGOUT_USER"
	}
}
export const item_Status ={
	item_Create :{
    NEW: "ADD_NEW",
		POST:"ADD_POST",
		AUTHORIZED: "LOGIN_ACCOUNT_AURHORIZED",
		FAILURE: "ADD_FAILURE",
		NOT_AUTHORIZED: "LOGIN_ACCOUNT_NOT_AUTHORIZED",
	CREATED:"ADD_CREATED",
	'LOGOUT':"LOGOUT_USER"
	}
}