export const manageteam_Actions = {

    NEW: "NEW_JOIN",
    SHOW: "SHOW_JOIN_TEAM_MEMBER",
    POSTED: "NEW_MEMBER_JOINED",
   
    // UPDATED: "UPDATE_LIY_MEMBER",
    // DELETED: "REMOVE_LIY_MEMBER",
    // UNDERUPDATE: "FETCH_MEMBER"
    // FIND:"TODO_FIND",
    // 	FAILURE: "ADD_FAILURE",
    // 	// NOT_AUTHORIZED: "LOGIN_ACCOUNT_NOT_AUTHORIZED",
    // CREATED:"ADD_CREATED",
    // 'LOGOUT':"LOGOUT_USER"

}
export const manageteam_Status = {

    NEW: "NEW_JOIN",
    SHOW: "NEW_MEMBER_JOINED",
    POSTED: "ADDED_NEW_MEMBER",
    FETCH_PLAYERS_TEAMS:"FETCH_ALL_PLAYERS_TEAMS"
    // UNDERUPDATE: "FETCH_MEMBER"

}